@startuml listOfComponents
title Découpage composants

package "My business/components" {
  [SideBar] 
  [Button]
  [Header]
  [APP]  
  [Pagination]
  [Table]
  [Select]
  [Checkbox]
}
package "MyBusiness/Features" {
  [DirectOrder]
  [StockReporing]
  [FixtureCatalog]
  [Franchise] 
}
package "MyBusiness/components/Header/components" {
  [User]
  [SearchBar]
  [Logo]
  [AppName]
}
package "MyBusiness/components/SideBar/components" {
  [CustomLink]
}
package "MyBusiness/components/Table/components" {
  [TableHeader]
  [TableRow]
  [TableData]
  [TableFooter]
}
package "MyBusiness/Features/Franchise/components" {
  [*Header]
}
@enduml
