
@startmindmap redux 
skinparam SequenceMessageAlignment center
skinparam classFontColor red

skinparam sequence {
ArrowColor black
}
skinparam State {
  BorderColor Gray
}

*[#SkyBlue]:globalState
**combineReducers**({
FranchiseState, 
  directOrderState,
  stockReportingState,
  fixtureCatalogState
});
**[#green]:FranchiseState
**combineReducers**({
  consolidations, 
  consolidationDetails
});
***[#LawnGreen]:Consolidations
-ConsolidationsSlice.js;
***[#LightGreen]:ConsolidationsDetails
-ConsolidationsDetailsSlice.js;
**[#yellow]:directOrderState
**combineReducers**({
  state1, 
  state2
});
***[#Gold]:State1
-State1Slice.js;
***[#GoldenRod]:State2
-State2Slice.js;
**[#grey]:stockReportingState
**combineReducers**({
  state1, 
  state2
});
***[#LightGray]:State1
-State1Slice.js;
***[#Gainsboro]:State2
-State2Slice.js;
**[#pink]:fixtureCatalogState
**combineReducers**({
  state1, 
  state2
});
***[#plum]:State1
-State1Slice.js;
***[#Thistle]:State2
-State2Slice.js;
@endmindmap